#!/bin/bash

# Get player
git submodule update --init --recursive

# Install player
cd app
yarn

# Override playlist
rm -rf src/mocks/ src/assets/
cp -r ../data/src/mocks src
cp -r ../data/src/assets src

# Build player
yarn build
cd ..

# Build Docker image
# docker build -t ffor .

