#!/bin/bash

# Get player
git submodule update --init --recursive

# Create build service
dbuild="docker run -it --rm -v $(pwd)/app:/src -w /src node:16.9.0-alpine";

# Install player
cd app
$dbuild yarn

# Override playlist
rm -rf src/mocks/ src/assets/
cp -r ../data/src/mocks src
cp -r ../data/src/assets src

# Build player
$dbuild yarn build
cd ..

# Build Docker image
# docker build -t ffor .

