version: '3.6'

services:
  app:
    image: ghcr.io/vergissberlin/frankfurtoder-rockt.de:main
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app/dist:/app/public:ro
    ports:
      - '8080:8080'
